In [1]:
import pandas as pd
from pathlib import Path

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

In [2]:
DATA_PATH = Path("../data/processed/synthetic_feature_engineered.csv")

df = pd.read_csv(DATA_PATH)

In [3]:
features = [
    "age_months",
    "sex",
    "weight_kg",
    "height_cm",
    "muac_cm",
    "waz",
    "haz",
    "whz",
    "bmi"
]

X = df[features]

In [4]:
y = df["underweight_status"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [6]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),

    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
}

In [7]:
results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)

    precision = precision_score(
        y_test,
        predictions,
        average="weighted"
    )

    recall = recall_score(
        y_test,
        predictions,
        average="weighted"
    )

    f1 = f1_score(
        y_test,
        predictions,
        average="weighted"
    )

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1
    ])

c:\Users\USER\OneDrive\Desktop\AI-Pediatric-Malnutrition-Detection\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [8]:
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

results_df

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression     0.992    0.99202   0.992  0.991992
1        Decision Tree     1.000    1.00000   1.000  1.000000
2        Random Forest     1.000    1.00000   1.000  1.000000

In [9]:
best_model = results_df.sort_values(
    by="Accuracy",
    ascending=False
)

best_model

                 Model  Accuracy  Precision  Recall  F1 Score
1        Decision Tree     1.000    1.00000   1.000  1.000000
2        Random Forest     1.000    1.00000   1.000  1.000000
0  Logistic Regression     0.992    0.99202   0.992  0.991992

In [10]:
import joblib
from pathlib import Path

best_model_name = best_model.iloc[0]["Model"]

selected_model = models[best_model_name]

model_dir = Path("../models")
model_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(
    selected_model,
    model_dir / "best_model.pkl"
)

print(f"{best_model_name} saved successfully!")

Decision Tree saved successfully!

In [11]:
results_df.to_csv(
    "../reports/model_comparison.csv",
    index=False
)